name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Install prerquisites
      run: |
       sudo apt-get update
       sudo apt-get install \
         libxi-dev libxrandr-dev \
         ccache asciidoc liblablgl-ocaml-dev libgumbo-dev libharfbuzz-dev libjpeg-dev libopenjp2-7-dev libjbig2dec0-dev
    - name: download mupdf
      run: |
        mkdir build
        bash misc/getmupdf.sh build/mupdf
    - name: Build mupdf
      run: |
        cd build/mupdf
        make shared=no build=release
        sudo make prefix=/usr install
    - name: build llpp
      run: bash ahbs
